package com.orbix.api.modules.vehicleandequipmentmaintenance;

import java.util.List;

import javax.servlet.http.HttpServletRequest;

public interface MaintenanceJobCardIssueService {
	MaintenanceJobCardIssueResponseDTO get(Long id, HttpServletRequest request);
	MaintenanceJobCardIssueResponseDTO createMaintenanceJobCardIssue(MaintenanceJobCardRequestDTO maintenanceJobCardRequest, HttpServletRequest request);
	MaintenanceJobCardIssueResponseDTO openMaintenanceJobCardIssue(MaintenanceJobCardIssueRequestDTO maintenanceJobCardIssueRequest, HttpServletRequest request);
	MaintenanceJobCardIssueResponseDTO closeMaintenanceJobCardIssue(MaintenanceJobCardIssueRequestDTO maintenanceJobCardIssueRequest, HttpServletRequest request);
	MaintenanceJobCardIssueResponseDTO reopenMaintenanceJobCardIssue(MaintenanceJobCardIssueRequestDTO maintenanceJobCardIssueRequest, HttpServletRequest request);
	MaintenanceJobCardIssueResponseDTO removeMaintenanceJobCardIssue(MaintenanceJobCardIssueRequestDTO maintenanceJobCardIssueRequest, HttpServletRequest request);
	List<MaintenanceJobCardIssueResponseDTO> getMyJobs(HttpServletRequest request);
	MaintenanceJobCardIssueResponseDTO saveComments(MaintenanceJobCardIssueRequestDTO maintenanceJobCardIssueRequest, HttpServletRequest request);
}
