package com.orbix.api.modules.vehicleandequipmentmaintenance;

import java.util.List;

import javax.servlet.http.HttpServletRequest;

public interface MaintenanceJobCardIssueBillReceivableService {
	public List<MaintenanceJobCardIssueBillReceivableResponseDTO> getAllByMaintenance(Long maintenanceId, HttpServletRequest request);
	public boolean deleteMaintenanceJobCardIssueBillReceivable(MaintenanceJobCardIssueBillReceivableRequestDTO maintenanceJobCardIssueBillReceivableRequestDTO, HttpServletRequest request);	
	//public MaintenanceJobCardIssueBillReceivableResponseDTO createMaintenanceJobCardIssueBillReceivable(MaintenanceJobCardIssueBillReceivableRequestDTO maintenanceJobCardIssueBillReceivableRequestDTO, HttpServletRequest request);
	public MaintenanceJobCardIssueBillReceivableResponseDTO updateMaintenanceJobCardIssueBillReceivable(MaintenanceJobCardIssueBillReceivableRequestDTO maintenanceJobCardIssueBillReceivableRequestDTO, HttpServletRequest request);	
	public MaintenanceJobCardIssueBillReceivableResponseDTO getMaintenanceJobCardIssueBillReceivable(Long id, HttpServletRequest request);
}
